register: true

registry:
  url: http://registry:8080

endpoint:
  port: 9080

healthchecks:
  - type: http
    value: http://localhost:80/
    interval: 30s
    timeout: 15s
    method: GET
    code: 200

commands:
  - cmd: [ "node", "authservice_app.js" ]
    on_exit: terminate

log_level: debug
